version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: monthly
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: django
    versions:
    - ">= 2.2.1.a, < 2.2.2"
  - dependency-name: django
    versions:
    - ">= 2.2.2.a, < 2.2.3"
  - dependency-name: django-debug-toolbar
    versions:
    - "< 1.10.2, >= 1.10.1.a"
  - dependency-name: ipython
    versions:
    - "< 6.6, >= 6.5.a"
  - dependency-name: selenium
    versions:
    - "< 3.14.1, >= 3.14.0.a"
  - dependency-name: selenium
    versions:
    - "< 3.142, >= 3.141.a"
  - dependency-name: selenium
    versions:
    - "< 3.15, >= 3.14.a"
  - dependency-name: sendgrid
    versions:
    - "< 5.6, >= 5.5.a"
  - dependency-name: sphinx
    versions:
    - "< 1.8, > 1.7.6"
  - dependency-name: django
    versions:
    - 3.1.5
    - 3.1.7
  - dependency-name: sendgrid
    versions:
    - 6.4.8
    - 6.5.0
  - dependency-name: sphinx
    versions:
    - 3.4.1
    - 3.4.3
  - dependency-name: ipython
    versions:
    - 7.19.0
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ajv
    versions:
    - ">= 6.10.a, < 6.11"
  - dependency-name: eslint
    versions:
    - "< 6, >= 5.a"
  - dependency-name: feather-icons
    versions:
    - ">= 4.15.a, < 4.16"
  - dependency-name: gulp-rename
    versions:
    - "> 1.2.3"
  - dependency-name: stylelint
    versions:
    - "< 9.6, >= 9.5.a"
  - dependency-name: ajv
    versions:
    - 7.0.2
    - 7.0.3
    - 7.1.1
  - dependency-name: core-js
    versions:
    - 3.8.3
    - 3.9.1
  - dependency-name: "@sentry/browser"
    versions:
    - 5.29.2
    - 6.0.3
    - 6.2.0
  - dependency-name: "@sentry/integrations"
    versions:
    - 5.29.2
    - 6.0.3
    - 6.2.0
  - dependency-name: "@vue/cli-plugin-babel"
    versions:
    - 4.5.11
  - dependency-name: d3
    versions:
    - 6.5.0
