files: [
 {
  "source" : "/tabbycat/**/locale/en/LC_MESSAGES/*.po",
  "translation" : "/tabbycat/**/locale/%two_letters_code%/LC_MESSAGES/%original_file_name%",
  "update_option" : "update_as_unapproved",
 },
 {
  "source" : "/docs/locale/en/LC_MESSAGES/**/*.po",
  "translation" : "/docs/locale/%two_letters_code%/LC_MESSAGES/**/%original_file_name%",
  "update_option" : "update_as_unapproved",
 }
]
